Web/GourmeJunk.Web/Areas/Admin/Controllers/CouponController.cs
using GourmeJunk.Common;
using GourmeJunk.Models.InputModels._AdminInputModels;
using GourmeJunk.Models.ViewModels.Coupons;
using GourmeJunk.Services.Contracts;
using GourmeJunk.Web.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GourmeJunk.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
    public class CouponController : Controller
    {
        private readonly ICouponsService couponsService;

        public CouponController(ICouponsService couponsService)
        {
            this.couponsService = couponsService;
        }

        public async Task<IActionResult> Index()
        {
            var couponsViewModels = await this.couponsService.GetAllCouponsViewModelsAsync();

            return View(couponsViewModels);
        }

        public IActionResult Create()
        {
            return View(new CouponCreateViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CouponCreateInputModel model)
        {
            var alreadyExists = await this.couponsService.CheckIfCouponExistsAsync(model.Name);

            if (alreadyExists || !ModelState.IsValid)
            {
                var couponCreateViewModel = new CouponCreateViewModel();

                if (alreadyExists)
                {
                    couponCreateViewModel.StatusMessage = string.Format(WebConstants.Error.ENTITY_ALREADY_EXISTS, model.Name);
                }

                couponCreateViewModel.Name = model.Name;
                couponCreateViewModel.CouponType = model.CouponType.ToString();
                couponCreateViewModel.Discount = model.Discount;
                couponCreateViewModel.MinimumOrderAmount = model.MinimumOrderAmount;
                couponCreateViewModel.IsActive = model.IsActive;

                return View(couponCreateViewModel);
            }

            var image = HttpContext.Request.Form.Files.Count > 0
                 ? HttpContext.Request.Form.Files[0]
                 : null;

            await this.couponsService.CreateCouponAsync(model, image);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(string id)
        {
            var couponEditViewModel = await this.couponsService.GetCouponModelByIdAsync<CouponViewModelExtended>(id);                            

            return View(couponEditViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CouponEditInputModel model)
        {            
            var alreadyExists = await this.couponsService.CheckIfAnotherCouponWithTheSameNameExistsAsync(model.Id, model.Name);

            if (alreadyExists || !ModelState.IsValid)
            {
                var couponEditViewModel = await this.couponsService.GetCouponModelByIdAsync<CouponViewModelExtended>(model.Id);

                if (alreadyExists)
                {
                    couponEditViewModel.StatusMessage =
                        string.Format(WebConstants.Error.ENTITY_ALREADY_EXISTS, $"{model.Name}");
                }

                return View(couponEditViewModel);
            }

            var image = HttpContext.Request.Form.Files.Count > 0
                ? HttpContext.Request.Form.Files[0]
                : null;

            await this.couponsService.EditCouponAsync(model, image);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            var couponDetailsModel = await this.couponsService.GetCouponModelByIdAsync<CouponViewModelExtended>(id);

            return View(couponDetailsModel);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var couponDeleteModel = await this.couponsService.GetCouponModelByIdAsync<CouponViewModelExtended>(id);

            return View(couponDeleteModel);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(string id)
        {
            await this.couponsService.DeleteCouponAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/GourmeJunk.Web/Areas/Admin/Controllers/UserController.cs
using GourmeJunk.Common;
using GourmeJunk.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GourmeJunk.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
    public class UserController : Controller
    {
        private readonly IUsersService usersService;

        public UserController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public async Task<IActionResult> Index()
        {
            var usersViewModels = await this.usersService.GetAllUsersViewModels();

            return View(usersViewModels);
        }

        public async Task<IActionResult> Lock(string id)
        {
            await this.usersService.LockUserAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            await this.usersService.UnLockUserAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Web/GourmeJunk.Web/Controllers/OrderController.cs
using GourmeJunk.Common;
using GourmeJunk.Models.ViewModels.Orders;
using GourmeJunk.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GourmeJunk.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrdersService ordersService;

        public OrderController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Confirm(string orderId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var OrderFullInfoViewModel = await this.ordersService.GetOrderFullInfoViewModelAsync(orderId, userId);

            return View(OrderFullInfoViewModel);
        }

        [Authorize]
        public async Task<IActionResult> OrderHistory(int productPage = 1)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var ordersHistoryViewModel = await this.ordersService.GetOrdersListViewModelAsync(productPage, userId);

            return View(ordersHistoryViewModel);
        }

        [Authorize]
        public async Task<IActionResult> GetOrderDetails(string id)
        {            
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var model = new OrderFullInfoViewModel();

            if (User.IsInRole(GlobalConstants.ADMINISTRATOR_ROLE_NAME) || User.IsInRole(GlobalConstants.RECEPTION_ROLE_NAME))
            {
                model = await this.ordersService.GetOrderFullInfoViewModelAsync(id, null);
            }
            else
            {
                model = await this.ordersService.GetOrderFullInfoViewModelAsync(id, userId);
            }        

            return PartialView("_IndividualOrderDetails", model);
        }

        [Authorize]
        public async Task<IActionResult> GetOrderStatus(string id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var orderStatus = await this.ordersService.GetOrderStatusAsync(id, userId);

            return PartialView("_OrderStatus", orderStatus);
        }

        [Authorize(Roles = 
            GlobalConstants.KITCHEN_ROLE_NAME + "," 
            + GlobalConstants.RECEPTION_ROLE_NAME + ","
            + GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
        public async Task<IActionResult> ManageOrders(int productPage = 1)
        {
            var manageOrdersListViewModel = await this.ordersService.GetManageOrdersListViewModelAsync(productPage);

            return View(manageOrdersListViewModel);
        }

        [Authorize(Roles = GlobalConstants.KITCHEN_ROLE_NAME + "," + GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
        public async Task<IActionResult> OrderPrepare(string id)
        {
            await this.ordersService.UpdateOrderStatusToCookingAsync(id);

            return RedirectToAction(nameof(ManageOrders));
        }

        [Authorize(Roles = GlobalConstants.KITCHEN_ROLE_NAME + "," + GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
        public async Task<IActionResult> OrderReady(string id)
        {
            await this.ordersService.UpdateOrderStatusToReadyAsync(id);

            return RedirectToAction(nameof(ManageOrders));
        }

        [Authorize(Roles = 
            GlobalConstants.KITCHEN_ROLE_NAME + "," + 
            GlobalConstants.ADMINISTRATOR_ROLE_NAME + "," +
            GlobalConstants.RECEPTION_ROLE_NAME)]
        public async Task<IActionResult> OrderCancel(string id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.ordersService.UpdateOrderStatusToCancelledAsync(id, userId);

            return RedirectToAction(nameof(ManageOrders));
        }

        [Authorize(Roles = GlobalConstants.RECEPTION_ROLE_NAME + "," + GlobalConstants.ADMINISTRATOR_ROLE_NAME)]
        public async Task<IActionResult> OrderPickup(string searchEmail, string searchPhone, string searchName, int productPage = 1)
        {            
            var ordersPickupViewModel = await this.ordersService.GetOrdersPickupListViewModelAsync(productPage, searchEmail, searchPhone, searchName);

            return View(ordersPickupViewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ADMINISTRATOR_ROLE_NAME + "," + GlobalConstants.RECEPTION_ROLE_NAME)]        
        [ActionName(nameof(OrderPickup))]
        public async Task<IActionResult> OrderPickupPost(string id)
        {
            await this.ordersService.UpdateOrderStatusToDeliveredAsync(id);            

            return RedirectToAction(nameof(OrderPickup));
        }
    }
}

Web/GourmeJunk.Web/Controllers/ShoppingCartController.cs
using GourmeJunk.Models.InputModels.Orders;
using GourmeJunk.Models.ViewModels.Orders;
using GourmeJunk.Services.Contracts;
using GourmeJunk.Web.Common;
using GourmeJunk.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GourmeJunk.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly IOrdersService ordersService;
        private readonly IUsersService usersService;

        public ShoppingCartController(
            IShoppingCartService shoppingCartService,
            IOrdersService ordersService,
            IUsersService usersService)
        {
            this.shoppingCartService = shoppingCartService;
            this.ordersService = ordersService;
            this.usersService = usersService;
        }
        
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;

            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var shoppingCartOrderViewModel = await this.shoppingCartService.GetShoppingCartViewModelAsync(userId);

            var couponCode = HttpContext.Session.GetString(WebConstants.SESSION_NAME_COUPON_CODE);

            if (!string.IsNullOrWhiteSpace(couponCode))
            {
                shoppingCartOrderViewModel.CouponName = couponCode;

                shoppingCartOrderViewModel = await this.shoppingCartService.ApplyCouponToCartAsync(shoppingCartOrderViewModel);

                HttpContext.Session.SetString(WebConstants.SESSION_NAME_COUPON_CODE, string.Empty);
            }

            return View(shoppingCartOrderViewModel);
        }

        [Authorize]
        public IActionResult AddCoupon(string couponName)
        {
            if (!string.IsNullOrWhiteSpace(couponName))
            {
                HttpContext.Session.SetString(WebConstants.SESSION_NAME_COUPON_CODE, couponName);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString(WebConstants.SESSION_NAME_COUPON_CODE, string.Empty);
            
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> IncrementItemQuantity(string menuItemId)
        {
            var userId = GetUserId();

            await this.shoppingCartService.IncrementItemQuantityAsync(userId, menuItemId);            

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> DecrementItemQuantity(string menuItemId)
        {
            var userId = GetUserId();

            var itemIsToBeRemoved = await this.shoppingCartService.CheckIfItemIsLastAndIsToBeRemovedAsync(userId, menuItemId);

            if (itemIsToBeRemoved)
            {
                return RedirectToAction(nameof(RemoveItem), new { menuItemId });
            }
            else
            {
                await this.shoppingCartService.DecrementItemQuantityAsync(userId, menuItemId);
            }
                      
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> RemoveItem(string menuItemId)
        {
            var userId = GetUserId();

            await this.shoppingCartService.RemoveItemAsync(userId, menuItemId);

            var userIndividualItemsCount = await this.shoppingCartService.GetUserIndividualItemsCountAsync(userId);

            HttpContext.Session.SetInt32(WebConstants.SESSION_NAME_SHOPPING_CART_INDIVIDUAL_ITEMS_COUNT, userIndividualItemsCount);

            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        [Authorize]        
        public async Task<IActionResult> Index(OrderSummaryInputModel model)
        {
            var formData = HttpContext.Request.Form;

            var itemsIds = formData[WebConstants.OrderItem.ITEM_ID_PROPERTY];
            var itemsNames = formData[WebConstants.OrderItem.ITEM_NAME_PROPERTY];
            var itemsPrices = formData[WebConstants.OrderItem.ITEM_PRICE_PROPERTY];
            var itemsCount = formData[WebConstants.OrderItem.ITEM_COUNT_PROPERTY];

            var pickupName = await this.usersService.GetUserFirstLastNameByIdAsync(model.UserId);

            var orderSummaryViewModel = this.ordersService.GetOrderSummaryViewModel(model, itemsIds, itemsNames, itemsPrices, itemsCount, pickupName);

            TempData.Put(nameof(OrderSummaryViewModel), orderSummaryViewModel);

            return RedirectToAction(nameof(OrderSummary), orderSummaryViewModel.OrderItems);
        }
       
        [Authorize]
        public IActionResult OrderSummary()
        {
            var orderSummaryViewModel = TempData.Get<OrderSummaryViewModel>(nameof(OrderSummaryViewModel)) ?? new OrderSummaryViewModel();
            TempData.Remove(nameof(OrderSummaryViewModel));
            
            return View(orderSummaryViewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> OrderSummary(OrderInputModel model, string stripeEmail, string stripeToken)
        {                       
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            var formData = HttpContext.Request.Form;

            var itemsIds = formData[WebConstants.OrderItem.ITEM_ID_PROPERTY];            
            var itemsCount = formData[WebConstants.OrderItem.ITEM_COUNT_PROPERTY];
            
            var orderId = await this.ordersService.CreateOrderAsync(model, itemsIds, itemsCount, stripeEmail, stripeToken);

            HttpContext.Session.SetInt32(WebConstants.SESSION_NAME_SHOPPING_CART_INDIVIDUAL_ITEMS_COUNT, WebConstants.SESSION_SHOPPING_CART_INITIAL_INDIVIDUAL_ITEMS_COUNT);

            return RedirectToAction("Confirm", "Order", new { orderId });
        }

        private string GetUserId()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;

            return claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
    }
}

Web/GourmeJunk.Web/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
    </div>
</div>

Web/GourmeJunk.Web/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">
    <i class="fas fa-plus"></i>&nbsp; Create New
    </a>
</p>

Web/GourmeJunk.Web/Views/Shared/_DeleteAndBackToListButton.cshtml
@model string

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
    </div>
</div>

Web/GourmeJunk.Web/Views/Shared/_DetailsAndBackToListButton.cshtml
@model string

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
    </div>
</div>

Web/GourmeJunk.Web/Views/Shared/_Layout.cshtml
@using GourmeJunk.Common
@using GourmeJunk.Web.Common
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using GourmeJunk.Data.Models

@inject IHttpContextAccessor httpContextAccessor
@inject SignInManager<GourmeJunkUser> signInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GourmeJunk</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />
    </environment>
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <div class="siteInfo">
        <button type="button" class="siteInfoBtn btn" data-toggle="modal" data-target="#siteInfoModal">
           <i class="fas fa-info-circle"></i> Information
        </button>
    </div>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-lg-3">
            <a class="navbar-brand text-light" href="/">GourmeJunk</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-flex justify-content-lg-between" id="navbarNav">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav d-md-flex flex-row order-lg-1">
                    @if (User.IsInRole(GlobalConstants.ADMINISTRATOR_ROLE_NAME))
                    {
                        <li class="nav-item dropdown mr-3 mr-lg-1">
                            <a class="nav-link dropdown-toggle text-light"
                               href="#"
                               id="navbarDropDownMenuLink"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu p-0" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item"
                                   asp-area="Admin"
                                   asp-controller="Category"
                                   asp-action="Index">Categories</a>
                                <a class="dropdown-item"
                                   asp-area="Admin"
                                   asp-controller="SubCategory"
                                   asp-action="Index">
                                    SubCategories
                                </a>
                                <a class="dropdown-item"
                                   asp-area="Admin"
                                   asp-controller="MenuItem"
                                   asp-action="Index">
                                    Menu Items
                                </a>
                                <a class="dropdown-item"
                                   asp-area="Admin"
                                   asp-controller="Coupon"
                                   asp-action="Index">
                                    Coupons
                                </a>
                                <a class="dropdown-item"
                                   asp-area="Admin"
                                   asp-controller="User"
                                   asp-action="Index">
                                    Users
                                </a>
                            </div>
                        </li>
                    }

                    @if (httpContextAccessor.HttpContext.Session.GetInt32(@WebConstants.SESSION_NAME_SHOPPING_CART_INDIVIDUAL_ITEMS_COUNT) != null)
                    {
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="mr-3 mr-lg-1" style="color:white">
                                <a href="/Order/OrderHistory" class="nav-link">
                                    <span class="text-white">Order History</span>
                                </a>
                            </li>

                            @if (User.IsInRole(GlobalConstants.KITCHEN_ROLE_NAME)
                            || User.IsInRole(GlobalConstants.RECEPTION_ROLE_NAME)
                            || User.IsInRole(GlobalConstants.ADMINISTRATOR_ROLE_NAME))
                            {
                                <li class="nav-item dropdown text-white-50 mr-3 mr-lg-1">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Orders
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                        @if (User.IsInRole(GlobalConstants.KITCHEN_ROLE_NAME) || User.IsInRole(GlobalConstants.ADMINISTRATOR_ROLE_NAME))
                                        {
                                            <a class="dropdown-item" href="/Order/ManageOrders">Manage Orders</a>
                                        }
                                        @if (User.IsInRole(GlobalConstants.RECEPTION_ROLE_NAME) || User.IsInRole(GlobalConstants.ADMINISTRATOR_ROLE_NAME))
                                        {
                                            <a class="dropdown-item" href="/Order/OrderPickup">Orders Pickup</a>
                                        }
                                    </div>
                                </li>
                            }

                            <li style="color:white;">
                                <a asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                    @{
                                        var userIndividualItemsCount = httpContextAccessor.HttpContext.Session.GetInt32(WebConstants.SESSION_NAME_SHOPPING_CART_INDIVIDUAL_ITEMS_COUNT);
                                    }
                                    <i class="fas fa-shopping-cart text-warning"></i>&nbsp; <span class="text-warning">(@userIndividualItemsCount)</span>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="p-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light" style="background-color: #343a40">
        <div class="container-fluid pl-4">
            &copy; @DateTime.Now.Year - GourmeJunk
        </div>
    </footer>

    <!-- SiteInfo Modal -->
    <div class="modal fade" id="siteInfoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title font-weight-bold" id="exampleModalLabel">GourmeJunk - Demo</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5 class="font-weight-bold">Test account:</h5>
                    <p class="mb-1">Username/email: test@gourmejunk.com</p>
                    <p>Password: 123456</p>

                    <h5 class="font-weight-bold">How to pay for an order:</h5>
                    <p class="mb-1">The website is using Stripe Web API (in Test Mode) for online payments. In order to pay, please, use the following credentials:</p>
                    <ul>
                        <li>Email: any random email</li>
                        <li>Card Number: 4242424242424242</li>
                        <li>Date: any random future date</li>
                        <li>CVC: any random 3-digit number</li>
                    </ul>

                    <p class="mb-0 font-weight-bold">For more info visit the website's git repository: <a target="_blank" href="https://github.com/volenpopov/GourmeJunk">Git Repo</a></p>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <button type="button" class="btn btn-secondary flex-grow-1" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        <script src="~/js/jquery-ui.js"></script>
        <script src="~/js/jquery.timepicker.min.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>